# Generated by Django 5.0.3 on 2024-03-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_name_task_name_rename_priority_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Priority',
            new_name='priority',
        ),
    ]
