# Generated by Django 5.0.3 on 2024-03-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_remove_task_name_task_field1'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
